// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: localrpc.proto

package localrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_localrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteCommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ExecuteCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_localrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteCommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ExecuteLuaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteLuaRequest) Reset() {
	*x = ExecuteLuaRequest{}
	mi := &file_localrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteLuaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteLuaRequest) ProtoMessage() {}

func (x *ExecuteLuaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteLuaRequest.ProtoReflect.Descriptor instead.
func (*ExecuteLuaRequest) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteLuaRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ExecuteLuaRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ExecuteLuaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteLuaResponse) Reset() {
	*x = ExecuteLuaResponse{}
	mi := &file_localrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteLuaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteLuaResponse) ProtoMessage() {}

func (x *ExecuteLuaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteLuaResponse.ProtoReflect.Descriptor instead.
func (*ExecuteLuaResponse) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteLuaResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteLuaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteLuaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint32                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_localrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryRequest) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetHistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_localrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetHistoryResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *GetHistoryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemasRequest) Reset() {
	*x = GetSchemasRequest{}
	mi := &file_localrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemasRequest) ProtoMessage() {}

func (x *GetSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemasRequest.ProtoReflect.Descriptor instead.
func (*GetSchemasRequest) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetSchemasRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type GetSchemasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemasJson   string                 `protobuf:"bytes,1,opt,name=schemas_json,json=schemasJson,proto3" json:"schemas_json,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemasResponse) Reset() {
	*x = GetSchemasResponse{}
	mi := &file_localrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemasResponse) ProtoMessage() {}

func (x *GetSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemasResponse.ProtoReflect.Descriptor instead.
func (*GetSchemasResponse) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{7}
}

func (x *GetSchemasResponse) GetSchemasJson() string {
	if x != nil {
		return x.SchemasJson
	}
	return ""
}

func (x *GetSchemasResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetSchemasResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsRequest) Reset() {
	*x = GetGroupsRequest{}
	mi := &file_localrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsRequest) ProtoMessage() {}

func (x *GetGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{8}
}

type GetGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        map[string]string      `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsResponse) Reset() {
	*x = GetGroupsResponse{}
	mi := &file_localrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsResponse) ProtoMessage() {}

func (x *GetGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsResponse) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{9}
}

func (x *GetGroupsResponse) GetGroups() map[string]string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetGroupsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetGroupsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CommandInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Usage         string                 `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	Ttp           string                 `protobuf:"bytes,5,opt,name=ttp,proto3" json:"ttp,omitempty"`
	Opsec         int32                  `protobuf:"varint,6,opt,name=opsec,proto3" json:"opsec,omitempty"`
	Subcommands   []string               `protobuf:"bytes,7,rep,name=subcommands,proto3" json:"subcommands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandInfo) Reset() {
	*x = CommandInfo{}
	mi := &file_localrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInfo) ProtoMessage() {}

func (x *CommandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInfo.ProtoReflect.Descriptor instead.
func (*CommandInfo) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{10}
}

func (x *CommandInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CommandInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandInfo) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *CommandInfo) GetTtp() string {
	if x != nil {
		return x.Ttp
	}
	return ""
}

func (x *CommandInfo) GetOpsec() int32 {
	if x != nil {
		return x.Opsec
	}
	return 0
}

func (x *CommandInfo) GetSubcommands() []string {
	if x != nil {
		return x.Subcommands
	}
	return nil
}

type SearchCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCommandsRequest) Reset() {
	*x = SearchCommandsRequest{}
	mi := &file_localrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCommandsRequest) ProtoMessage() {}

func (x *SearchCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCommandsRequest.ProtoReflect.Descriptor instead.
func (*SearchCommandsRequest) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{11}
}

func (x *SearchCommandsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchCommandsRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SearchCommandsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SearchCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CommandInfo         `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCommandsResponse) Reset() {
	*x = SearchCommandsResponse{}
	mi := &file_localrpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCommandsResponse) ProtoMessage() {}

func (x *SearchCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localrpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCommandsResponse.ProtoReflect.Descriptor instead.
func (*SearchCommandsResponse) Descriptor() ([]byte, []int) {
	return file_localrpc_proto_rawDescGZIP(), []int{12}
}

func (x *SearchCommandsResponse) GetCommands() []*CommandInfo {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *SearchCommandsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SearchCommandsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_localrpc_proto protoreflect.FileDescriptor

const file_localrpc_proto_rawDesc = "" +
	"\n" +
	"\x0elocalrpc.proto\x12\x11services.localrpc\"P\n" +
	"\x15ExecuteCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"`\n" +
	"\x16ExecuteCommandResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"J\n" +
	"\x11ExecuteLuaRequest\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\\\n" +
	"\x12ExecuteLuaResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"K\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\rR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\\\n" +
	"\x12GetHistoryResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\")\n" +
	"\x11GetSchemasRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\"g\n" +
	"\x12GetSchemasResponse\x12!\n" +
	"\fschemas_json\x18\x01 \x01(\tR\vschemasJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\x12\n" +
	"\x10GetGroupsRequest\"\xc8\x01\n" +
	"\x11GetGroupsResponse\x12H\n" +
	"\x06groups\x18\x01 \x03(\v20.services.localrpc.GetGroupsResponse.GroupsEntryR\x06groups\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x1a9\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\vCommandInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05usage\x18\x04 \x01(\tR\x05usage\x12\x10\n" +
	"\x03ttp\x18\x05 \x01(\tR\x03ttp\x12\x14\n" +
	"\x05opsec\x18\x06 \x01(\x05R\x05opsec\x12 \n" +
	"\vsubcommands\x18\a \x03(\tR\vsubcommands\"b\n" +
	"\x15SearchCommandsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x84\x01\n" +
	"\x16SearchCommandsResponse\x12:\n" +
	"\bcommands\x18\x01 \x03(\v2\x1e.services.localrpc.CommandInfoR\bcommands\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\xaf\x05\n" +
	"\x0eCommandService\x12e\n" +
	"\x0eExecuteCommand\x12(.services.localrpc.ExecuteCommandRequest\x1a).services.localrpc.ExecuteCommandResponse\x12f\n" +
	"\rStreamCommand\x12(.services.localrpc.ExecuteCommandRequest\x1a).services.localrpc.ExecuteCommandResponse0\x01\x12Y\n" +
	"\n" +
	"ExecuteLua\x12$.services.localrpc.ExecuteLuaRequest\x1a%.services.localrpc.ExecuteLuaResponse\x12Y\n" +
	"\n" +
	"GetHistory\x12$.services.localrpc.GetHistoryRequest\x1a%.services.localrpc.GetHistoryResponse\x12Y\n" +
	"\n" +
	"GetSchemas\x12$.services.localrpc.GetSchemasRequest\x1a%.services.localrpc.GetSchemasResponse\x12V\n" +
	"\tGetGroups\x12#.services.localrpc.GetGroupsRequest\x1a$.services.localrpc.GetGroupsResponse\x12e\n" +
	"\x0eSearchCommands\x12(.services.localrpc.SearchCommandsRequest\x1a).services.localrpc.SearchCommandsResponseBBZ@github.com/chainreactors/IoM-go/proto/services/localrpc;localrpcb\x06proto3"

var (
	file_localrpc_proto_rawDescOnce sync.Once
	file_localrpc_proto_rawDescData []byte
)

func file_localrpc_proto_rawDescGZIP() []byte {
	file_localrpc_proto_rawDescOnce.Do(func() {
		file_localrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_localrpc_proto_rawDesc), len(file_localrpc_proto_rawDesc)))
	})
	return file_localrpc_proto_rawDescData
}

var file_localrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_localrpc_proto_goTypes = []any{
	(*ExecuteCommandRequest)(nil),  // 0: services.localrpc.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil), // 1: services.localrpc.ExecuteCommandResponse
	(*ExecuteLuaRequest)(nil),      // 2: services.localrpc.ExecuteLuaRequest
	(*ExecuteLuaResponse)(nil),     // 3: services.localrpc.ExecuteLuaResponse
	(*GetHistoryRequest)(nil),      // 4: services.localrpc.GetHistoryRequest
	(*GetHistoryResponse)(nil),     // 5: services.localrpc.GetHistoryResponse
	(*GetSchemasRequest)(nil),      // 6: services.localrpc.GetSchemasRequest
	(*GetSchemasResponse)(nil),     // 7: services.localrpc.GetSchemasResponse
	(*GetGroupsRequest)(nil),       // 8: services.localrpc.GetGroupsRequest
	(*GetGroupsResponse)(nil),      // 9: services.localrpc.GetGroupsResponse
	(*CommandInfo)(nil),            // 10: services.localrpc.CommandInfo
	(*SearchCommandsRequest)(nil),  // 11: services.localrpc.SearchCommandsRequest
	(*SearchCommandsResponse)(nil), // 12: services.localrpc.SearchCommandsResponse
	nil,                            // 13: services.localrpc.GetGroupsResponse.GroupsEntry
}
var file_localrpc_proto_depIdxs = []int32{
	13, // 0: services.localrpc.GetGroupsResponse.groups:type_name -> services.localrpc.GetGroupsResponse.GroupsEntry
	10, // 1: services.localrpc.SearchCommandsResponse.commands:type_name -> services.localrpc.CommandInfo
	0,  // 2: services.localrpc.CommandService.ExecuteCommand:input_type -> services.localrpc.ExecuteCommandRequest
	0,  // 3: services.localrpc.CommandService.StreamCommand:input_type -> services.localrpc.ExecuteCommandRequest
	2,  // 4: services.localrpc.CommandService.ExecuteLua:input_type -> services.localrpc.ExecuteLuaRequest
	4,  // 5: services.localrpc.CommandService.GetHistory:input_type -> services.localrpc.GetHistoryRequest
	6,  // 6: services.localrpc.CommandService.GetSchemas:input_type -> services.localrpc.GetSchemasRequest
	8,  // 7: services.localrpc.CommandService.GetGroups:input_type -> services.localrpc.GetGroupsRequest
	11, // 8: services.localrpc.CommandService.SearchCommands:input_type -> services.localrpc.SearchCommandsRequest
	1,  // 9: services.localrpc.CommandService.ExecuteCommand:output_type -> services.localrpc.ExecuteCommandResponse
	1,  // 10: services.localrpc.CommandService.StreamCommand:output_type -> services.localrpc.ExecuteCommandResponse
	3,  // 11: services.localrpc.CommandService.ExecuteLua:output_type -> services.localrpc.ExecuteLuaResponse
	5,  // 12: services.localrpc.CommandService.GetHistory:output_type -> services.localrpc.GetHistoryResponse
	7,  // 13: services.localrpc.CommandService.GetSchemas:output_type -> services.localrpc.GetSchemasResponse
	9,  // 14: services.localrpc.CommandService.GetGroups:output_type -> services.localrpc.GetGroupsResponse
	12, // 15: services.localrpc.CommandService.SearchCommands:output_type -> services.localrpc.SearchCommandsResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_localrpc_proto_init() }
func file_localrpc_proto_init() {
	if File_localrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_localrpc_proto_rawDesc), len(file_localrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_localrpc_proto_goTypes,
		DependencyIndexes: file_localrpc_proto_depIdxs,
		MessageInfos:      file_localrpc_proto_msgTypes,
	}.Build()
	File_localrpc_proto = out.File
	file_localrpc_proto_goTypes = nil
	file_localrpc_proto_depIdxs = nil
}
